### ISSUE TITLE
os.path.abspath failing due to os.getcwd() fail

### ISSUE THREAD

**Issue by djhmateer** [bellingcat/auto-archiver#97]
Related to https://github.com/bellingcat/auto-archiver/issues/96 which fixed another issue

```py
# unknown why it fails on second time
# this will fail as the call to os.getcwd() fails
# https://stackoverflow.com/questions/3210902/python-why-does-os-getcwd-sometimes-crash-with-oserror
# bar = os.path.abspath(foo)
# but if we fix with using psutil way, then get errors further down with shutil copying

# browsertrix_home_host = os.environ.get('BROWSERTRIX_HOME_HOST') or os.path.abspath(ArchivingContext.get_tmp_dir())
# hard code path fixes it for now
browsertrix_home_host = '/mnt/c/dev/v6-auto-archiver' + ArchivingContext.get_tmp_dir()[1:]


browsertrix_home_container = os.environ.get('BROWSERTRIX_HOME_CONTAINER') or browsertrix_home_host
```

The error is:

```
File "/mnt/c/dev/v6-auto-archiver/src/auto_archiver/enrichers/wacz_enricher.py", line 54, in enrich
bar = os.path.abspath(foo)
File "/usr/lib/python3.10/posixpath.py", line 384, in abspath
  cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

This could be my platform (WSL2) so I'll try on another server.

Have been looking to see how to turn off the deletion of the tmp directory to see if that helps (haven't found out how to do that yet)

**Comment by msramalho** [comment]
can you confirm that everything was working at [this commit](https://github.com/bellingcat/auto-archiver/blob/main/src/auto_archiver/enrichers/wacz_enricher.py?rgh-link-date=2023-09-15T12%3A32%3A46Z#L50) and that it still does not work after [this fix](https://github.com/bellingcat/auto-archiver/commit/ea38a604bbec9b531460ed3dc7507d32e74ec2b2)?

for the tmp dir, since we use the `with` operator it will always get destroyed once the execution leaves that block, no way I can think of going around it. you could modify the ArchivingContext to use a stationary folder.

**Comment by msramalho** [comment]
Given it so far seems a WSL specific issue we wont work on this but welcome external contributions, and hope you can find a solution.
